server:
  port: 7000

spring:
  application:
    name: Accounts

  datasource:
    url : jdbc:h2:mem:accounts
    username: admin
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    spring:
      jpa:
        data-base-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
