server:
  port: 8000
spring:
  application:
    name: MyUsers
  datasource:
    url: jdbc:h2:mem:my_users
    username: admin
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    spring:
      jpa:
        data-base-platform: org.hibernate.dialect.H2Dialect

    defer-datasource-initialization: true

    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

