spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    enabled: false
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
info:
  app:
    name: My notes
    version: v0.0