server:
  port: 9000
spring:
  datasource:
#    url: jdbc:h2:mem:users
#    driverClassName: org.h2.Driver
#    username: user
#    password: 1234
    initialization-mode: always
#    defer-datasource-initialization: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#      generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    h2:
      console:
        enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
