server:
  port: 9000
spring:

  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:9000/login

  datasource:
    url: jdbc:h2:mem:users
    driverClassName: org.h2.Driver
    username: user
    password: 1234

  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    defer-datasource-initialization: true

    hibernate:
      ddl-auto: update

    show-sql: true

    sql:
      init:
        mode: always

    h2:
      console:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
