server:
  port: 8080


spring:
  security:
    oauth2:
      authorization-server:
        client:
          demo-client:
            require-authorization-consent: true
            registration:
              client-id: client
              client-secret: "secret"
              authorization-grant-types: client_credentials,authorization_code,refresh_token
              redirect-uris: http://127.0.0.1:8080/login/oauth2/code/reg-client
              scopes: user.read,user.write,openid
              client-authentication-methods: client_secret_basic
  datasource:
    url: jdbc:h2:mem://localhost:7000
    driverClassName: org.h2.Driver
    username: user
    password: 1234
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        security: trace