server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
        registration:
          reg-client:
            provider: spring
            client-id: test-client
            client-secret: test-client
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://127.0.0.1:8080/login"
            scope: user.read,openid


  mvc:
    log-request-details: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: trace
#    org.springframework.security.oauth2: INFO
#    #    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE